### ISSUE TITLE
FR/Idea: For MSK, use Cluster ARN for `bootstrapServers`

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#102]
Currently the default configuration for MSK uses the same pattern as for other Kafka clusters, with the difference that you would most likely use IAM authentication, and have

```yaml
clusters:
  - id: amazon-msk-iam
    name: Amazon MSK IAM
    color: #FF9900
    bootstrapServers: "b-3-public.****.kafka.eu-west-1.amazonaws.com:9198"
    properties: |
      security.protocol=SASL_SSL
      sasl.mechanism=AWS_MSK_IAM
      sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class=io.conduktor.aws.IAMClientCallbackHandler
```

What if, instead of using the list of `bootstrapServers` for MSK, one would use the cluster ARN?
The ARN of a MSK cluster has [a very simple regular expression](https://github.com/compose-x/compose-x-common/blob/main/src/compose_x_common/aws/msk.py#L18)
Assuming that the Conduktor platform runs with access to AWS Credentials, most likely the same as the ones that will be used to connect to said cluster, using the MSK API with the cluster ARN would allow to programmatically retrieve the **correct** endpoints.

Given that MSK uses different ports based on whether the cluster is public or private, this would also allow for a "fool-proof" deployment.

So one would get

```yaml
clusters:
  - id: amazon-msk-iam
    name: Amazon MSK IAM
    color: #FF9900
    bootstrapServers: arn:aws:msk:eu-west-1:000111222333:cluster/ClusterName/uuid
    properties: |
      security.protocol=SASL_SSL
      sasl.mechanism=AWS_MSK_IAM
      sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class=io.conduktor.aws.IAMClientCallbackHandler
```

Now, for the SaaS deployment of Conduktor, this would require to be granted permissions by the user to access the service.

This can be done "simply" via IAM roles.
If Conduktor SaaS runs on AWS already, it's simple to allow users to provide Conduktor a role ARN that can be assumed to perform all MSK API calls (also avoids an AWS MSK user to have to create an IAM "user", create access and secret keys and give them to Conduktor).

In fact, in the SaaS version, when adding a MSK cluster, via ARN, most of the properties can be subsequently generated by testing out connectivity to the cluster using the provided MSK Cluster ARN and IAM Role ARN.
