### ISSUE TITLE
Cant connect to schema registry?

### ISSUE THREAD

**Issue by BlankWheein** [conduktor/conduktor-platform#138]
unsure if this is an Conduktor issue or if its the schema registry setup but, with this configuration of the Schema registry i can not connect to it using conduktor

```yml
kafka-schema-registry:
    image: confluentinc/cp-schema-registry:7.3.2
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka1:19092,PLAINTEXT://kafka2:19093,PLAINTEXT://kafka3:19094'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
```

i get the following error
![image](https://user-images.githubusercontent.com/47646799/222248230-a8f35f29-75c8-419a-8665-eb762a8c923b.png)
i can connect to the clusters just fine, and it says it can connect to the schema registry just that i dont have the right authentication, any ideas on what i can do?
