### ISSUE TITLE
Endless loop on localhost:8080

### ISSUE THREAD

**Issue by zklgame** [conduktor/conduktor-platform#159]
When running the `conduktor/conduktor-platform:latest` image and visiting the `localhost:8080`, got the error:
```
POST http://localhost:8080/graphql 405 (Not Allowed)
Navigated to http://localhost:8080/index.html
```
It resulted in endless loop on the page.

############################################
Browser: Chrome. Version 116.0.5845.179 (Official Build) (x86_64)

The related part in the docker-compose.yml from this [file](https://github.com/conduktor/kafka-beginners-course/blob/main/conduktor-platform/docker-compose.yml):
```
  conduktor-platform:
    image: conduktor/conduktor-platform:latest
    ports:
      - 8080:8080
    volumes:
      - conduktor_data:/var/conduktor
      - type: bind
        source: "./platform-config.yml"
        target: /opt/conduktor/platform-config.yaml
        read_only: true
    depends_on:
      - kafka1
      - kafka-schema-registry
    environment:
      CDK_IN_CONF_FILE: /opt/conduktor/platform-config.yaml
      KAFKA_BOOTSTRAP_SERVER: PLAINTEXT://kafka1:19092
      SR_SERVER: "http://kafka-schema-registry:8081"
      ORGANISATION_NAME: "default"
      CDK_ADMIN_EMAIL: "admin@conduktor.io"
      CDK_ADMIN_PASSWORD: "admin"
```
