### ISSUE TITLE
No web UI

### ISSUE THREAD

**Issue by remynollet** [conduktor/conduktor-platform#18]
Trying the example-local, there is no UI looking http://localhost:80

How can we access to the console ?

**Comment by remynollet** [comment]
It seems that our zscaler proxy on our laptop is allready use the port 80.
I try to map 
```
  conduktor-platform:
    image: conduktor/conduktor-platform:latest
    #network_mode: "bridge"
    ports:
      - 8000:80
```
the http://localhost:8000 is redirect to http://localhost/home

And 
```
HTTP Error 404. The requested resource is not found.
```
