### ISSUE TITLE
Your schema configuration is invalid

### ISSUE THREAD

**Issue by remynollet** [conduktor/conduktor-platform#19]
I have this error to connect my Aiven SR
```
Your schema configuration is invalid
Defining a cluster is required for connecting to a Kafka broker. It also enables you to use related services such as Schema Registry.
```
But my config seems ok

```yml
    schemaRegistry:
      id: xxx-dev-01
      url: "https://public-xxx-dev-01-peered-xx.aivencloud.com:12661"
      ignoreUntrustedCertificate: false
      security:
        username: "avnadmin"
        password: "xxxx"
```

**Comment by framiere** [comment]
@twobeeb

**Comment by twobeeb** [comment]
Hi @remynollet,
It looks correct, would you mind sharing the entire `clusters` configuration block?
On my side I have no issue connecting to Aiven SR with the following configuration example:

````
clusters: 
  - id: example
    name: Example
    ignoreUntrustedCertificate: false
    bootstrapServers: "broker:9092"
    properties: |
      security.protocol=SASL_SSL
      sasl.mechanism=PLAIN
      sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username='***'   password='***';
    schemaRegistry:
      id: xxx-dev-01
      url: "https://***-europe-kafka-***.aivencloud.com:21653"
      ignoreUntrustedCertificate: false
      security:
        username: avnadmin
        password: ******
````

Also, could you ensure the registry is properly reachable from where you are deploying
